import type { Product, Money, FlavourProfile } from "@whiskymart/types";

/* Small builders to keep the seed data readable. */
const gbp = (amount: number): Money => ({ amount, currency: "GBP" });

const flav = (p: Partial<FlavourProfile>): FlavourProfile => ({
  smoky: 0,
  peaty: 0,
  sweet: 0,
  fruity: 0,
  spicy: 0,
  floral: 0,
  maritime: 0,
  rich: 0,
  ...p,
});

/**
 * Seed catalogue. This is a stand-in for the real product service (Medusa /
 * API). The repository ({@link ./repository}) is the only thing that touches
 * it, so swapping the source later requires no UI changes.
 */
export const SEED_PRODUCTS: Product[] = [
  {
    id: "p_lagavulin16",
    type: "bottle",
    title: "Lagavulin 16 Year Old",
    slug: "lagavulin-16-year-old",
    brand: { id: "b_lagavulin", name: "Lagavulin", slug: "lagavulin" },
    distillery: { id: "d_lagavulin", name: "Lagavulin", slug: "lagavulin", region: "islay", foundedYear: 1816 },
    bottlerType: "OB",
    status: "active",
    description:
      "A towering Islay single malt: deep, dry and smoky, with the seaweed-led peat Lagavulin is famous for, balanced by rich sweetness and a long, elegant finish.",
    story:
      "Matured for sixteen years on the southern shore of Islay, this is the benchmark by which peated whiskies are judged.",
    whisky: { abv: 43, ageYears: 16, region: "islay", caskType: ["ex-bourbon"], peatPpm: 35, chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [
      { id: "v_lag16_70", sku: "LAG16-70", sizeMl: 700, price: gbp(7495), memberPrice: gbp(6745), inStock: true },
      { id: "v_lag16_3cl", sku: "LAG16-3CL", sizeMl: 30, price: gbp(695), inStock: true },
    ],
    image: { seed: "lagavulin", alt: "Bottle of Lagavulin 16 Year Old single malt Scotch whisky" },
    flavour: flav({ smoky: 85, peaty: 80, maritime: 70, sweet: 40, rich: 55 }),
    tastingNote: {
      nose: "Intense peat smoke with iodine and seaweed, layered over rich sweetness.",
      palate: "Dry, powerful smoke with sea salt, sherry and a touch of espresso.",
      finish: "Long, elegant and smoky.",
    },
    flavourTags: ["smoky", "peaty", "maritime"],
    ratingAvg: 4.7,
    ratingCount: 212,
    badges: ["bestseller", "award"],
  },
  {
    id: "p_glenfiddich12",
    type: "bottle",
    title: "Glenfiddich 12 Year Old",
    slug: "glenfiddich-12-year-old",
    brand: { id: "b_glenfiddich", name: "Glenfiddich", slug: "glenfiddich" },
    distillery: { id: "d_glenfiddich", name: "Glenfiddich", slug: "glenfiddich", region: "speyside", foundedYear: 1887 },
    bottlerType: "OB",
    status: "active",
    description:
      "One of the world's biggest-selling single malts and a natural first step into Speyside. Fresh pear, cream and gentle oak, with nothing to trip over.",
    whisky: { abv: 40, ageYears: 12, region: "speyside", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_gf12_70", sku: "GF12-70", sizeMl: 700, price: gbp(3995), memberPrice: gbp(3595), inStock: true }],
    image: { seed: "glenfiddich", alt: "Bottle of Glenfiddich 12 Year Old single malt Scotch whisky" },
    flavour: flav({ sweet: 65, fruity: 75, floral: 45, rich: 30 }),
    tastingNote: {
      nose: "Fresh pear and subtle oak.",
      palate: "Sweet, fruity and creamy with a hint of butterscotch.",
      finish: "Long and mellow.",
    },
    flavourTags: ["sweet", "fruity", "beginner"],
    ratingAvg: 4.5,
    ratingCount: 488,
    badges: ["bestseller"],
  },
  {
    id: "p_ardbeg10",
    type: "bottle",
    title: "Ardbeg 10 Year Old",
    slug: "ardbeg-10-year-old",
    brand: { id: "b_ardbeg", name: "Ardbeg", slug: "ardbeg" },
    distillery: { id: "d_ardbeg", name: "Ardbeg", slug: "ardbeg", region: "islay", foundedYear: 1815 },
    bottlerType: "OB",
    status: "active",
    description:
      "A cult Islay classic, bottled at 46% and non-chill-filtered. Uncompromising peat smoke wrapped around surprising notes of lime, pear and vanilla.",
    whisky: { abv: 46, ageYears: 10, region: "islay", caskType: ["ex-bourbon"], peatPpm: 55, chillFiltered: false, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_ard10_70", sku: "ARD10-70", sizeMl: 700, price: gbp(5295), memberPrice: gbp(4895), inStock: true }],
    image: { seed: "ardbeg", alt: "Bottle of Ardbeg 10 Year Old single malt Scotch whisky" },
    flavour: flav({ smoky: 90, peaty: 88, maritime: 55, sweet: 35, fruity: 40 }),
    tastingNote: {
      nose: "Smoke, tar and zesty citrus.",
      palate: "Powerful peat with espresso, pear and a savoury edge.",
      finish: "Very long and smoky.",
    },
    flavourTags: ["smoky", "peaty"],
    ratingAvg: 4.8,
    ratingCount: 357,
    badges: ["award"],
  },
  {
    id: "p_glenmorangie10",
    type: "bottle",
    title: "Glenmorangie The Original 10 Year Old",
    slug: "glenmorangie-original-10",
    brand: { id: "b_glenmorangie", name: "Glenmorangie", slug: "glenmorangie" },
    distillery: { id: "d_glenmorangie", name: "Glenmorangie", slug: "glenmorangie", region: "highland", foundedYear: 1843 },
    bottlerType: "OB",
    status: "active",
    description:
      "Distilled at Scotland's tallest stills for a delicate, elegant spirit. Floral and citrus-led with peach, vanilla and a creamy texture.",
    whisky: { abv: 40, ageYears: 10, region: "highland", caskType: ["ex-bourbon"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_glm10_70", sku: "GLM10-70", sizeMl: 700, price: gbp(3795), memberPrice: gbp(3415), inStock: true }],
    image: { seed: "glenmorangie", alt: "Bottle of Glenmorangie The Original 10 Year Old single malt" },
    flavour: flav({ floral: 80, fruity: 70, sweet: 55, spicy: 25 }),
    tastingNote: {
      nose: "Peach, citrus and floral honey.",
      palate: "Vanilla, orange and a creamy malt sweetness.",
      finish: "Clean and fragrant.",
    },
    flavourTags: ["floral", "fruity", "beginner"],
    ratingAvg: 4.4,
    ratingCount: 274,
    badges: [],
  },
  {
    id: "p_macallan12",
    type: "bottle",
    title: "The Macallan 12 Year Old Sherry Oak",
    slug: "macallan-12-sherry-oak",
    brand: { id: "b_macallan", name: "The Macallan", slug: "macallan" },
    distillery: { id: "d_macallan", name: "The Macallan", slug: "macallan", region: "speyside", foundedYear: 1824 },
    bottlerType: "OB",
    status: "active",
    description:
      "Matured exclusively in hand-picked sherry-seasoned oak casks from Jerez. Rich, full-bodied and unmistakably Macallan: dried fruit, ginger and Christmas spice.",
    whisky: { abv: 40, ageYears: 12, region: "speyside", caskType: ["ex-sherry"], chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_mac12_70", sku: "MAC12-70", sizeMl: 700, price: gbp(8495), memberPrice: gbp(7645), inStock: true }],
    image: { seed: "macallan", alt: "Bottle of The Macallan 12 Year Old Sherry Oak single malt" },
    flavour: flav({ rich: 85, sweet: 60, spicy: 55, fruity: 50 }),
    tastingNote: {
      nose: "Dried fruits, sherry and wood smoke.",
      palate: "Rich, full and rounded with ginger and dried fruit.",
      finish: "Sweet oak, long.",
    },
    flavourTags: ["rich", "sherried"],
    ratingAvg: 4.6,
    ratingCount: 401,
    badges: ["exclusive", "bestseller"],
  },
  {
    id: "p_talisker10",
    type: "bottle",
    title: "Talisker 10 Year Old",
    slug: "talisker-10-year-old",
    brand: { id: "b_talisker", name: "Talisker", slug: "talisker" },
    distillery: { id: "d_talisker", name: "Talisker", slug: "talisker", region: "islands", foundedYear: 1830 },
    bottlerType: "OB",
    status: "active",
    description:
      "The classic maritime malt from the Isle of Skye, peppery smoke, brine and a famous pinch of sea salt, with warming sweetness underneath.",
    whisky: { abv: 45.8, ageYears: 10, region: "islands", caskType: ["ex-bourbon"], peatPpm: 25, chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_tal10_70", sku: "TAL10-70", sizeMl: 700, price: gbp(4495), memberPrice: gbp(4045), inStock: true }],
    image: { seed: "talisker", alt: "Bottle of Talisker 10 Year Old single malt Scotch whisky" },
    flavour: flav({ smoky: 60, maritime: 80, spicy: 65, sweet: 40 }),
    tastingNote: {
      nose: "Sea spray, smoke and citrus.",
      palate: "Peppery smoke, brine and barley sweetness.",
      finish: "Warm with a peppery kick.",
    },
    flavourTags: ["maritime", "smoky", "spicy"],
    ratingAvg: 4.6,
    ratingCount: 319,
    badges: ["bestseller"],
  },
  {
    id: "p_redbreast12",
    type: "bottle",
    title: "Redbreast 12 Year Old",
    slug: "redbreast-12-year-old",
    brand: { id: "b_redbreast", name: "Redbreast", slug: "redbreast" },
    distillery: { id: "d_midleton", name: "Midleton", slug: "midleton", region: "ireland", foundedYear: 1825 },
    bottlerType: "OB",
    status: "active",
    description:
      "The definitive single pot still Irish whiskey. Full and complex, with the spicy, creamy character that only pot still distillation delivers.",
    whisky: { abv: 40, ageYears: 12, region: "ireland", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_rb12_70", sku: "RB12-70", sizeMl: 700, price: gbp(5995), memberPrice: gbp(5395), inStock: true }],
    image: { seed: "redbreast", alt: "Bottle of Redbreast 12 Year Old single pot still Irish whiskey" },
    flavour: flav({ rich: 70, fruity: 65, spicy: 60, sweet: 55 }),
    tastingNote: {
      nose: "Dried fruit, toasted oak and pot still spices.",
      palate: "Full and creamy with sherry, nuts and spice.",
      finish: "Satisfying and long.",
    },
    flavourTags: ["rich", "spicy", "fruity"],
    ratingAvg: 4.7,
    ratingCount: 263,
    badges: ["award"],
  },
  {
    id: "p_hibiki_harmony",
    type: "bottle",
    title: "Hibiki Japanese Harmony",
    slug: "hibiki-japanese-harmony",
    brand: { id: "b_hibiki", name: "Hibiki", slug: "hibiki" },
    distillery: { id: "d_suntory", name: "Suntory", slug: "suntory", region: "japan", foundedYear: 1923 },
    bottlerType: "OB",
    status: "active",
    description:
      "A blend of malt and grain whiskies from Suntory's Yamazaki, Hakushu and Chita distilleries. Delicate, harmonious and subtly floral.",
    whisky: { abv: 43, ageYears: null, region: "japan", caskType: ["ex-bourbon", "ex-sherry", "mizunara"], chillFiltered: true, naturalColour: false, limitedEdition: true },
    variants: [{ id: "v_hib_70", sku: "HIB-70", sizeMl: 700, price: gbp(8995), memberPrice: gbp(8095), inStock: true }],
    image: { seed: "hibiki", alt: "Bottle of Hibiki Japanese Harmony blended whisky" },
    flavour: flav({ floral: 75, fruity: 60, sweet: 55, rich: 40 }),
    tastingNote: {
      nose: "Rose, lychee and a hint of sandalwood.",
      palate: "Honey, candied orange and white chocolate.",
      finish: "Subtle Mizunara oak.",
    },
    flavourTags: ["floral", "delicate", "japanese"],
    ratingAvg: 4.5,
    ratingCount: 158,
    badges: ["limited", "new"],
  },
  {
    id: "p_islay_flight",
    type: "sample",
    title: "Islay Discovery: Tasting Flight (4 × 3cl)",
    slug: "islay-discovery-tasting-flight",
    brand: { id: "b_whiskymart", name: "WhiskyMart Selection", slug: "whiskymart-selection" },
    bottlerType: "NA",
    status: "active",
    description:
      "Four 3cl samples of benchmark Islay malts, a low-risk way to find your favourite before committing to a full bottle. Includes Lagavulin, Ardbeg, Laphroaig and Bowmore.",
    whisky: { abv: 46, ageYears: null, region: "islay", caskType: [], peatPpm: 50, limitedEdition: false },
    variants: [{ id: "v_flight_islay", sku: "FLIGHT-ISLAY", sizeMl: 120, price: gbp(2495), inStock: true }],
    image: { seed: "islay-flight", alt: "Islay whisky tasting flight of four 3cl samples" },
    flavour: flav({ smoky: 85, peaty: 82, maritime: 60 }),
    flavourTags: ["smoky", "peaty", "sample", "flight"],
    ratingAvg: 4.8,
    ratingCount: 96,
    badges: ["new"],
  },
  {
    id: "p_glencairn_glass",
    type: "accessory",
    title: "Glencairn Crystal Whisky Glass (Set of 2)",
    slug: "glencairn-whisky-glass-set-of-2",
    brand: { id: "b_glencairn", name: "Glencairn", slug: "glencairn" },
    bottlerType: "NA",
    status: "active",
    description:
      "The official whisky nosing and tasting glass, designed to concentrate aromas. Tapered mouth, solid base, dishwasher safe. Sold as a set of two.",
    variants: [{ id: "v_glencairn_2", sku: "GLEN-GLASS-2", sizeMl: 0, price: gbp(1600), inStock: true }],
    image: { seed: "glencairn", alt: "Set of two Glencairn crystal whisky tasting glasses" },
    flavourTags: ["accessory", "glassware"],
    ratingAvg: 4.9,
    ratingCount: 134,
    badges: [],
  },
  /* ------------------------------------------------------------------ */
  /* Islay                                                               */
  /* ------------------------------------------------------------------ */
  {
    id: "p_laphroaig10",
    type: "bottle",
    title: "Laphroaig 10 Year Old",
    slug: "laphroaig-10-year-old",
    brand: { id: "b_laphroaig", name: "Laphroaig", slug: "laphroaig" },
    distillery: { id: "d_laphroaig", name: "Laphroaig", slug: "laphroaig", region: "islay", foundedYear: 1815 },
    bottlerType: "OB",
    status: "active",
    description:
      "The most medicinal of the Islay malts, and proudly so. Ten years in ex-bourbon casks gives seaweed, iodine and a big peat hit with a surprisingly sweet middle. People rarely feel neutral about it.",
    whisky: { abv: 40, ageYears: 10, region: "islay", caskType: ["ex-bourbon"], peatPpm: 40, chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [
      { id: "v_lap10_70", sku: "LAP10-70", sizeMl: 700, price: gbp(4495), memberPrice: gbp(4045), inStock: true },
      { id: "v_lap10_3cl", sku: "LAP10-3CL", sizeMl: 30, price: gbp(495), inStock: true },
    ],
    image: { seed: "laphroaig", alt: "Bottle of Laphroaig 10 Year Old single malt Scotch whisky" },
    flavour: flav({ smoky: 88, peaty: 90, maritime: 75, sweet: 30 }),
    tastingNote: {
      nose: "Iodine, seaweed and cold bonfire ash.",
      palate: "Big peat, sea salt and a sweet, malty core.",
      finish: "Long, dry and smoky.",
    },
    flavourTags: ["smoky", "peaty", "maritime"],
    ratingAvg: 4.6,
    ratingCount: 0,
    badges: ["bestseller"],
  },
  {
    id: "p_bowmore12",
    type: "bottle",
    title: "Bowmore 12 Year Old",
    slug: "bowmore-12-year-old",
    brand: { id: "b_bowmore", name: "Bowmore", slug: "bowmore" },
    distillery: { id: "d_bowmore", name: "Bowmore", slug: "bowmore", region: "islay", foundedYear: 1779 },
    bottlerType: "OB",
    status: "active",
    description:
      "Islay's oldest distillery makes the island's most balanced dram. Medium peat, honey and citrus in roughly equal measure, which makes this the Islay bottle for people still deciding whether they like Islay.",
    whisky: { abv: 40, ageYears: 12, region: "islay", caskType: ["ex-bourbon", "ex-sherry"], peatPpm: 25, chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_bow12_70", sku: "BOW12-70", sizeMl: 700, price: gbp(4395), memberPrice: gbp(3955), inStock: true }],
    image: { seed: "bowmore", alt: "Bottle of Bowmore 12 Year Old single malt Scotch whisky" },
    flavour: flav({ smoky: 55, peaty: 50, maritime: 55, sweet: 50, fruity: 40 }),
    tastingNote: {
      nose: "Lemon, honey and gentle peat smoke.",
      palate: "Warm smoke over toffee and citrus.",
      finish: "Medium, smoky and slightly salty.",
    },
    flavourTags: ["smoky", "maritime", "sweet"],
    ratingAvg: 4.3,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_bunnahabhain12",
    type: "bottle",
    title: "Bunnahabhain 12 Year Old",
    slug: "bunnahabhain-12-year-old",
    brand: { id: "b_bunnahabhain", name: "Bunnahabhain", slug: "bunnahabhain" },
    distillery: { id: "d_bunnahabhain", name: "Bunnahabhain", slug: "bunnahabhain", region: "islay", foundedYear: 1881 },
    bottlerType: "OB",
    status: "active",
    description:
      "The Islay malt without the smoke. Unpeated, sherry-led and bottled at 46.3% without chill-filtration or added colour, it tastes of dried fruit, brine and walnuts. The island's best-kept open secret.",
    whisky: { abv: 46.3, ageYears: 12, region: "islay", caskType: ["ex-sherry", "ex-bourbon"], chillFiltered: false, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_bun12_70", sku: "BUN12-70", sizeMl: 700, price: gbp(4995), memberPrice: gbp(4495), inStock: true }],
    image: { seed: "bunnahabhain", alt: "Bottle of Bunnahabhain 12 Year Old single malt Scotch whisky" },
    flavour: flav({ rich: 65, maritime: 55, fruity: 55, sweet: 50 }),
    tastingNote: {
      nose: "Sherry, sea air and roasted nuts.",
      palate: "Dried fruit and brine with a creamy texture.",
      finish: "Nutty and gently salty.",
    },
    flavourTags: ["rich", "maritime", "sherried"],
    ratingAvg: 4.5,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_caolila12",
    type: "bottle",
    title: "Caol Ila 12 Year Old",
    slug: "caol-ila-12-year-old",
    brand: { id: "b_caolila", name: "Caol Ila", slug: "caol-ila" },
    distillery: { id: "d_caolila", name: "Caol Ila", slug: "caol-ila", region: "islay", foundedYear: 1846 },
    bottlerType: "OB",
    status: "active",
    description:
      "Islay's biggest distillery and its lightest touch with peat. Grassy, olive-oil smooth smoke with grapefruit underneath. Blenders have prized it for decades; drinkers are catching up.",
    whisky: { abv: 43, ageYears: 12, region: "islay", caskType: ["ex-bourbon"], peatPpm: 30, chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_ci12_70", sku: "CI12-70", sizeMl: 700, price: gbp(5995), memberPrice: gbp(5395), inStock: true }],
    image: { seed: "caolila", alt: "Bottle of Caol Ila 12 Year Old single malt Scotch whisky" },
    flavour: flav({ smoky: 65, peaty: 60, maritime: 60, fruity: 45 }),
    tastingNote: {
      nose: "Fresh smoke, cut grass and citrus.",
      palate: "Smooth, oily smoke with grapefruit and sweet malt.",
      finish: "Clean and lightly smoky.",
    },
    flavourTags: ["smoky", "peaty", "maritime"],
    ratingAvg: 4.4,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_kilchoman_machirbay",
    type: "bottle",
    title: "Kilchoman Machir Bay",
    slug: "kilchoman-machir-bay",
    brand: { id: "b_kilchoman", name: "Kilchoman", slug: "kilchoman" },
    distillery: { id: "d_kilchoman", name: "Kilchoman", slug: "kilchoman", region: "islay", foundedYear: 2005 },
    bottlerType: "OB",
    status: "active",
    description:
      "Islay's farm distillery, founded in 2005 and already essential. Machir Bay marries young ex-bourbon casks with a little oloroso for big, clean peat smoke and vanilla. Proof that age statements are not the whole story.",
    whisky: { abv: 46, ageYears: null, region: "islay", caskType: ["ex-bourbon", "ex-sherry"], peatPpm: 50, chillFiltered: false, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_kil_mb_70", sku: "KIL-MB-70", sizeMl: 700, price: gbp(5295), memberPrice: gbp(4765), inStock: true }],
    image: { seed: "kilchoman", alt: "Bottle of Kilchoman Machir Bay single malt Scotch whisky" },
    flavour: flav({ smoky: 80, peaty: 78, maritime: 60, sweet: 40, fruity: 35 }),
    tastingNote: {
      nose: "Crisp peat smoke, vanilla and sea spray.",
      palate: "Sweet smoke, lemon and a saline edge.",
      finish: "Long, smoky and fresh.",
    },
    flavourTags: ["smoky", "peaty", "maritime"],
    ratingAvg: 4.4,
    ratingCount: 0,
    badges: ["new"],
  },
  /* ------------------------------------------------------------------ */
  /* Speyside                                                            */
  /* ------------------------------------------------------------------ */
  {
    id: "p_glenlivet12",
    type: "bottle",
    title: "The Glenlivet 12 Year Old",
    slug: "glenlivet-12-year-old",
    brand: { id: "b_glenlivet", name: "The Glenlivet", slug: "glenlivet" },
    distillery: { id: "d_glenlivet", name: "The Glenlivet", slug: "glenlivet", region: "speyside", foundedYear: 1824 },
    bottlerType: "OB",
    status: "active",
    description:
      "The first licensed distillery in the glen and still the definition of soft Speyside style. Pineapple, vanilla and cream from American and European oak. If someone tells you they don't like whisky, pour them this before you believe them.",
    whisky: { abv: 40, ageYears: 12, region: "speyside", caskType: ["ex-bourbon", "european-oak"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_gl12_70", sku: "GL12-70", sizeMl: 700, price: gbp(3895), memberPrice: gbp(3505), inStock: true }],
    image: { seed: "glenlivet", alt: "Bottle of The Glenlivet 12 Year Old single malt Scotch whisky" },
    flavour: flav({ fruity: 70, sweet: 65, floral: 50, rich: 25 }),
    tastingNote: {
      nose: "Pineapple, vanilla and spring flowers.",
      palate: "Soft, creamy orchard fruit and toffee.",
      finish: "Gentle and clean.",
    },
    flavourTags: ["fruity", "sweet", "beginner"],
    ratingAvg: 4.3,
    ratingCount: 0,
    badges: ["bestseller"],
  },
  {
    id: "p_balvenie12",
    type: "bottle",
    title: "The Balvenie DoubleWood 12 Year Old",
    slug: "balvenie-doublewood-12",
    brand: { id: "b_balvenie", name: "The Balvenie", slug: "balvenie" },
    distillery: { id: "d_balvenie", name: "The Balvenie", slug: "balvenie", region: "speyside", foundedYear: 1892 },
    bottlerType: "OB",
    status: "active",
    description:
      "Twelve years in ex-bourbon casks, then a final stretch in first-fill oloroso butts. The sherry finish adds honeyed depth and a nutty sweetness to Balvenie's already generous house style. One of the great everyday malts.",
    whisky: { abv: 40, ageYears: 12, region: "speyside", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_bal12_70", sku: "BAL12-70", sizeMl: 700, price: gbp(4895), memberPrice: gbp(4405), inStock: true }],
    image: { seed: "balvenie", alt: "Bottle of The Balvenie DoubleWood 12 Year Old single malt" },
    flavour: flav({ sweet: 70, rich: 55, fruity: 50, spicy: 40 }),
    tastingNote: {
      nose: "Honey, vanilla and a layer of sherry.",
      palate: "Nutty sweetness, cinnamon and orchard fruit.",
      finish: "Warm and lightly spiced.",
    },
    flavourTags: ["sweet", "rich"],
    ratingAvg: 4.5,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_aberlour12",
    type: "bottle",
    title: "Aberlour 12 Year Old Double Cask",
    slug: "aberlour-12-double-cask",
    brand: { id: "b_aberlour", name: "Aberlour", slug: "aberlour" },
    distillery: { id: "d_aberlour", name: "Aberlour", slug: "aberlour", region: "speyside", foundedYear: 1879 },
    bottlerType: "OB",
    status: "active",
    description:
      "Matured in a mix of ex-bourbon and sherry casks and married for balance. Red apple, dark chocolate and soft spice. France drinks more Aberlour than anywhere else on earth, and the French are rarely wrong about these things.",
    whisky: { abv: 40, ageYears: 12, region: "speyside", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_ab12_70", sku: "AB12-70", sizeMl: 700, price: gbp(4395), memberPrice: gbp(3955), inStock: true }],
    image: { seed: "aberlour", alt: "Bottle of Aberlour 12 Year Old Double Cask single malt" },
    flavour: flav({ sweet: 60, fruity: 60, rich: 50, spicy: 35 }),
    tastingNote: {
      nose: "Red apple, sherry and soft caramel.",
      palate: "Chocolate, raisin and gentle oak spice.",
      finish: "Sweet and rounded.",
    },
    flavourTags: ["sweet", "fruity", "sherried"],
    ratingAvg: 4.3,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_glenfarclas105",
    type: "bottle",
    title: "Glenfarclas 105 Cask Strength",
    slug: "glenfarclas-105-cask-strength",
    brand: { id: "b_glenfarclas", name: "Glenfarclas", slug: "glenfarclas" },
    distillery: { id: "d_glenfarclas", name: "Glenfarclas", slug: "glenfarclas", region: "speyside", foundedYear: 1836 },
    bottlerType: "OB",
    status: "active",
    description:
      "Family-owned since 1865 and still doing sherry casks the old way. The 105 is bottled at 60%, the old 105 British proof, and delivers dense dried fruit and gingerbread with real heat. Add water. Then add a little more.",
    whisky: { abv: 60, ageYears: null, region: "speyside", caskType: ["ex-sherry"], chillFiltered: false, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_gf105_70", sku: "GF105-70", sizeMl: 700, price: gbp(5295), memberPrice: gbp(4765), inStock: true }],
    image: { seed: "glenfarclas", alt: "Bottle of Glenfarclas 105 cask strength single malt" },
    flavour: flav({ rich: 85, sweet: 60, spicy: 65, fruity: 50 }),
    tastingNote: {
      nose: "Dense sherry, dark fruit cake and oak.",
      palate: "Powerful gingerbread, raisin and dark chocolate.",
      finish: "Very long, drying and warm.",
    },
    flavourTags: ["rich", "sherried", "spicy"],
    ratingAvg: 4.6,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_benriach12",
    type: "bottle",
    title: "Benriach The Twelve",
    slug: "benriach-the-twelve",
    brand: { id: "b_benriach", name: "Benriach", slug: "benriach" },
    distillery: { id: "d_benriach", name: "Benriach", slug: "benriach", region: "speyside", foundedYear: 1898 },
    bottlerType: "OB",
    status: "active",
    description:
      "Twelve years across sherry, bourbon and port casks, bottled at 46%. The three-cask recipe gives baked fruit and cocoa with more weight than most Speysiders at this price. Quietly one of the region's better deals.",
    whisky: { abv: 46, ageYears: 12, region: "speyside", caskType: ["ex-sherry", "ex-bourbon", "port"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_br12_70", sku: "BR12-70", sizeMl: 700, price: gbp(4695), memberPrice: gbp(4225), inStock: true }],
    image: { seed: "benriach", alt: "Bottle of Benriach The Twelve single malt Scotch whisky" },
    flavour: flav({ rich: 60, sweet: 60, fruity: 55, spicy: 40 }),
    tastingNote: {
      nose: "Baked apple, cocoa and dark honey.",
      palate: "Stewed fruit, chocolate and warm oak.",
      finish: "Medium, sweet and lightly spiced.",
    },
    flavourTags: ["rich", "sweet", "fruity"],
    ratingAvg: 4.2,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_glenfiddich18",
    type: "bottle",
    title: "Glenfiddich 18 Year Old",
    slug: "glenfiddich-18-year-old",
    brand: { id: "b_glenfiddich", name: "Glenfiddich", slug: "glenfiddich" },
    distillery: { id: "d_glenfiddich", name: "Glenfiddich", slug: "glenfiddich", region: "speyside", foundedYear: 1887 },
    bottlerType: "OB",
    status: "active",
    description:
      "Eighteen years in oloroso sherry and bourbon casks, married in small batches. The pear of the 12 grows up into baked apple, candied peel and oak. A dependable step into older whisky without the price shock.",
    whisky: { abv: 40, ageYears: 18, region: "speyside", caskType: ["ex-sherry", "ex-bourbon"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_gf18_70", sku: "GF18-70", sizeMl: 700, price: gbp(8995), memberPrice: gbp(8095), inStock: true }],
    image: { seed: "glenfiddich18", alt: "Bottle of Glenfiddich 18 Year Old single malt Scotch whisky" },
    flavour: flav({ fruity: 65, rich: 60, sweet: 55, spicy: 35 }),
    tastingNote: {
      nose: "Baked apple, candied peel and oak.",
      palate: "Dried fruit, cinnamon and soft caramel.",
      finish: "Long, warm and rounded.",
    },
    flavourTags: ["fruity", "rich"],
    ratingAvg: 4.4,
    ratingCount: 0,
    badges: [],
  },
  /* ------------------------------------------------------------------ */
  /* Highland                                                            */
  /* ------------------------------------------------------------------ */
  {
    id: "p_oban14",
    type: "bottle",
    title: "Oban 14 Year Old",
    slug: "oban-14-year-old",
    brand: { id: "b_oban", name: "Oban", slug: "oban" },
    distillery: { id: "d_oban", name: "Oban", slug: "oban", region: "highland", foundedYear: 1794 },
    bottlerType: "OB",
    status: "active",
    description:
      "One of Scotland's smallest and oldest distilleries, wedged between a cliff and the harbour. Fourteen years gives orange peel, sea salt and a wisp of smoke. West Highland whisky with the coast built in.",
    whisky: { abv: 43, ageYears: 14, region: "highland", caskType: ["ex-bourbon"], peatPpm: 5, chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [
      { id: "v_oban14_70", sku: "OBAN14-70", sizeMl: 700, price: gbp(6495), memberPrice: gbp(5845), inStock: true },
      { id: "v_oban14_3cl", sku: "OBAN14-3CL", sizeMl: 30, price: gbp(595), inStock: true },
    ],
    image: { seed: "oban", alt: "Bottle of Oban 14 Year Old single malt Scotch whisky" },
    flavour: flav({ maritime: 65, fruity: 60, sweet: 50, smoky: 25 }),
    tastingNote: {
      nose: "Orange peel, sea spray and honey.",
      palate: "Dried fig, salt and a faint thread of smoke.",
      finish: "Long, smooth and gently maritime.",
    },
    flavourTags: ["maritime", "fruity"],
    ratingAvg: 4.5,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_glendronach12",
    type: "bottle",
    title: "The GlenDronach 12 Year Old Original",
    slug: "glendronach-12-original",
    brand: { id: "b_glendronach", name: "The GlenDronach", slug: "glendronach" },
    distillery: { id: "d_glendronach", name: "The GlenDronach", slug: "glendronach", region: "highland", foundedYear: 1826 },
    bottlerType: "OB",
    status: "active",
    description:
      "Sherry-cask whisky as it used to be made. Twelve years in Pedro Ximénez and oloroso casks for dark fruit, cocoa and a rich, oily body. The bottle sherry lovers point to when asked where to start.",
    whisky: { abv: 43, ageYears: 12, region: "highland", caskType: ["ex-sherry"], chillFiltered: false, naturalColour: true, limitedEdition: false },
    variants: [
      { id: "v_gd12_70", sku: "GD12-70", sizeMl: 700, price: gbp(4995), memberPrice: gbp(4495), inStock: true },
      { id: "v_gd12_3cl", sku: "GD12-3CL", sizeMl: 30, price: gbp(495), inStock: true },
    ],
    image: { seed: "glendronach", alt: "Bottle of The GlenDronach 12 Year Old Original single malt" },
    flavour: flav({ rich: 80, sweet: 65, fruity: 55, spicy: 45 }),
    tastingNote: {
      nose: "Stewed plum, PX sweetness and cocoa.",
      palate: "Dark fruit, chocolate and warm oak spice.",
      finish: "Long and generously sherried.",
    },
    flavourTags: ["rich", "sherried", "sweet"],
    ratingAvg: 4.6,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_dalmore12",
    type: "bottle",
    title: "The Dalmore 12 Year Old",
    slug: "dalmore-12-year-old",
    brand: { id: "b_dalmore", name: "The Dalmore", slug: "dalmore" },
    distillery: { id: "d_dalmore", name: "The Dalmore", slug: "dalmore", region: "highland", foundedYear: 1839 },
    bottlerType: "OB",
    status: "active",
    description:
      "Nine years in American white oak, then three in aged oloroso butts. Orange, chocolate and spice under the stag's head label. Dressier than most 12-year-olds, and it drinks the part.",
    whisky: { abv: 40, ageYears: 12, region: "highland", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_dal12_70", sku: "DAL12-70", sizeMl: 700, price: gbp(6495), memberPrice: gbp(5845), inStock: true }],
    image: { seed: "dalmore", alt: "Bottle of The Dalmore 12 Year Old single malt Scotch whisky" },
    flavour: flav({ rich: 70, sweet: 60, fruity: 55, spicy: 40 }),
    tastingNote: {
      nose: "Seville orange, sherry and dark chocolate.",
      palate: "Citrus marmalade, coffee and oak.",
      finish: "Warm with lingering orange.",
    },
    flavourTags: ["rich", "sweet"],
    ratingAvg: 4.2,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_clynelish14",
    type: "bottle",
    title: "Clynelish 14 Year Old",
    slug: "clynelish-14-year-old",
    brand: { id: "b_clynelish", name: "Clynelish", slug: "clynelish" },
    distillery: { id: "d_clynelish", name: "Clynelish", slug: "clynelish", region: "highland", foundedYear: 1819 },
    bottlerType: "OB",
    status: "active",
    description:
      "The famously waxy Highland malt. Candle wax sounds unappealing until you taste it: a thick, mouth-coating texture wrapped around citrus and honey. Blenders fight over the stock, which is why the single malt stays scarce.",
    whisky: { abv: 46, ageYears: 14, region: "highland", caskType: ["ex-bourbon"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_cly14_70", sku: "CLY14-70", sizeMl: 700, price: gbp(5295), memberPrice: gbp(4765), inStock: true }],
    image: { seed: "clynelish", alt: "Bottle of Clynelish 14 Year Old single malt Scotch whisky" },
    flavour: flav({ fruity: 60, maritime: 50, sweet: 50, floral: 40, rich: 40 }),
    tastingNote: {
      nose: "Beeswax, lemon and coastal air.",
      palate: "Waxy texture, honey and white pepper.",
      finish: "Long, waxy and slightly salty.",
    },
    flavourTags: ["fruity", "maritime"],
    ratingAvg: 4.5,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_glengoyne10",
    type: "bottle",
    title: "Glengoyne 10 Year Old",
    slug: "glengoyne-10-year-old",
    brand: { id: "b_glengoyne", name: "Glengoyne", slug: "glengoyne" },
    distillery: { id: "d_glengoyne", name: "Glengoyne", slug: "glengoyne", region: "highland", foundedYear: 1833 },
    bottlerType: "OB",
    status: "active",
    description:
      "Air-dried barley, no peat at all, and the slowest stills in Scotland by the distillery's own count. The result is clean, appley and gentle. An honest first bottle that never talks down to you.",
    whisky: { abv: 40, ageYears: 10, region: "highland", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_gg10_70", sku: "GG10-70", sizeMl: 700, price: gbp(3895), memberPrice: gbp(3505), inStock: true }],
    image: { seed: "glengoyne", alt: "Bottle of Glengoyne 10 Year Old single malt Scotch whisky" },
    flavour: flav({ fruity: 65, sweet: 55, floral: 40, rich: 25 }),
    tastingNote: {
      nose: "Green apple, toffee and cut hay.",
      palate: "Fresh fruit, malt and gentle oak.",
      finish: "Clean and soft.",
    },
    flavourTags: ["fruity", "sweet", "beginner"],
    ratingAvg: 4.2,
    ratingCount: 0,
    badges: [],
  },
  /* ------------------------------------------------------------------ */
  /* Islands                                                             */
  /* ------------------------------------------------------------------ */
  {
    id: "p_highlandpark12",
    type: "bottle",
    title: "Highland Park 12 Year Old Viking Honour",
    slug: "highland-park-12-viking-honour",
    brand: { id: "b_highlandpark", name: "Highland Park", slug: "highland-park" },
    distillery: { id: "d_highlandpark", name: "Highland Park", slug: "highland-park", region: "islands", foundedYear: 1798 },
    bottlerType: "OB",
    status: "active",
    description:
      "Orkney's balancing act: heather honey sweetness against a low hum of floor-malted peat, matured largely in sherry-seasoned oak. For the money, one of the most complete whiskies in Scotland.",
    whisky: { abv: 40, ageYears: 12, region: "islands", caskType: ["ex-sherry"], peatPpm: 20, chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_hp12_70", sku: "HP12-70", sizeMl: 700, price: gbp(3995), memberPrice: gbp(3595), inStock: true }],
    image: { seed: "highlandpark", alt: "Bottle of Highland Park 12 Year Old Viking Honour single malt" },
    flavour: flav({ sweet: 60, smoky: 40, peaty: 35, rich: 50, floral: 35 }),
    tastingNote: {
      nose: "Heather honey, gentle smoke and orange.",
      palate: "Sweet malt, dried fruit and a soft peaty base.",
      finish: "Medium, honeyed and lightly smoky.",
    },
    flavourTags: ["sweet", "smoky"],
    ratingAvg: 4.4,
    ratingCount: 0,
    badges: ["bestseller"],
  },
  {
    id: "p_jura10",
    type: "bottle",
    title: "Jura 10 Year Old",
    slug: "jura-10-year-old",
    brand: { id: "b_jura", name: "Jura", slug: "jura" },
    distillery: { id: "d_jura", name: "Jura", slug: "jura", region: "islands", foundedYear: 1810 },
    bottlerType: "OB",
    status: "active",
    description:
      "From the island with one road, one pub and one distillery. Ten years in ex-bourbon casks with an oloroso finishing touch. Soft, sweet and easy company, with just enough island character to place it on a map.",
    whisky: { abv: 40, ageYears: 10, region: "islands", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_jura10_70", sku: "JURA10-70", sizeMl: 700, price: gbp(3495), memberPrice: gbp(3145), inStock: true }],
    image: { seed: "jura", alt: "Bottle of Jura 10 Year Old single malt Scotch whisky" },
    flavour: flav({ sweet: 60, fruity: 50, maritime: 35, rich: 30 }),
    tastingNote: {
      nose: "Caramel, orange and a whisper of coast.",
      palate: "Soft toffee, malt and dried fruit.",
      finish: "Gentle and warming.",
    },
    flavourTags: ["sweet", "beginner"],
    ratingAvg: 4.0,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_arran10",
    type: "bottle",
    title: "Arran 10 Year Old",
    slug: "arran-10-year-old",
    brand: { id: "b_arran", name: "Arran", slug: "arran" },
    distillery: { id: "d_arran", name: "Arran", slug: "arran", region: "islands", foundedYear: 1995 },
    bottlerType: "OB",
    status: "active",
    description:
      "The modern island success story. Bottled at 46% without chill-filtration, it tastes of citrus, vanilla and clean malt with a saline edge. A young distillery that earned its shelf space the honest way.",
    whisky: { abv: 46, ageYears: 10, region: "islands", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: false, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_arr10_70", sku: "ARR10-70", sizeMl: 700, price: gbp(3995), memberPrice: gbp(3595), inStock: true }],
    image: { seed: "arran", alt: "Bottle of Arran 10 Year Old single malt Scotch whisky" },
    flavour: flav({ fruity: 60, sweet: 55, maritime: 40, floral: 35 }),
    tastingNote: {
      nose: "Citrus, vanilla and fresh malt.",
      palate: "Apple, honey and a light salty note.",
      finish: "Crisp and clean.",
    },
    flavourTags: ["fruity", "sweet"],
    ratingAvg: 4.3,
    ratingCount: 0,
    badges: [],
  },
  /* ------------------------------------------------------------------ */
  /* Campbeltown                                                         */
  /* ------------------------------------------------------------------ */
  {
    id: "p_springbank10",
    type: "bottle",
    title: "Springbank 10 Year Old",
    slug: "springbank-10-year-old",
    brand: { id: "b_springbank", name: "Springbank", slug: "springbank" },
    distillery: { id: "d_springbank", name: "Springbank", slug: "springbank", region: "campbeltown", foundedYear: 1828 },
    bottlerType: "OB",
    status: "active",
    story:
      "Every stage from malting to bottling happens on one site in Campbeltown, by hand, the way the whole town once did it. Allocations are small and sell through fast.",
    description:
      "Distilled two and a half times, lightly peated, and matured in bourbon and sherry casks. Oily, salty and faintly smoky, with more character per drop than almost anything at this age. The cult is justified.",
    whisky: { abv: 46, ageYears: 10, region: "campbeltown", caskType: ["ex-bourbon", "ex-sherry"], peatPpm: 12, chillFiltered: false, naturalColour: true, limitedEdition: false },
    variants: [
      { id: "v_sb10_70", sku: "SB10-70", sizeMl: 700, price: gbp(6495), inStock: true },
      { id: "v_sb10_3cl", sku: "SB10-3CL", sizeMl: 30, price: gbp(695), inStock: true },
    ],
    image: { seed: "springbank", alt: "Bottle of Springbank 10 Year Old single malt Scotch whisky" },
    flavour: flav({ maritime: 70, smoky: 45, peaty: 40, rich: 55, fruity: 45 }),
    tastingNote: {
      nose: "Brine, oil and orchard fruit.",
      palate: "Salty, waxy malt with soft smoke and vanilla.",
      finish: "Long, coastal and slightly earthy.",
    },
    flavourTags: ["maritime", "smoky", "rich"],
    ratingAvg: 4.8,
    ratingCount: 0,
    badges: ["award"],
  },
  {
    id: "p_glenscotia_dc",
    type: "bottle",
    title: "Glen Scotia Double Cask",
    slug: "glen-scotia-double-cask",
    brand: { id: "b_glenscotia", name: "Glen Scotia", slug: "glen-scotia" },
    distillery: { id: "d_glenscotia", name: "Glen Scotia", slug: "glen-scotia", region: "campbeltown", foundedYear: 1832 },
    bottlerType: "OB",
    status: "active",
    description:
      "The other survivor of Campbeltown's whisky collapse. First-fill bourbon casks finished in Pedro Ximénez give caramel and dried fruit over the town's trademark salty backbone. Underpriced for what it is.",
    whisky: { abv: 46, ageYears: null, region: "campbeltown", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: false, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_gs_dc_70", sku: "GS-DC-70", sizeMl: 700, price: gbp(4495), memberPrice: gbp(4045), inStock: true }],
    image: { seed: "glenscotia", alt: "Bottle of Glen Scotia Double Cask single malt Scotch whisky" },
    flavour: flav({ sweet: 60, maritime: 55, rich: 50, spicy: 40 }),
    tastingNote: {
      nose: "Caramel, sultana and sea air.",
      palate: "Vanilla, dried fruit and salted toffee.",
      finish: "Medium, sweet and briny.",
    },
    flavourTags: ["sweet", "maritime"],
    ratingAvg: 4.2,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_kilkerran12",
    type: "bottle",
    title: "Kilkerran 12 Year Old",
    slug: "kilkerran-12-year-old",
    brand: { id: "b_kilkerran", name: "Kilkerran", slug: "kilkerran" },
    distillery: { id: "d_glengyle", name: "Glengyle", slug: "glengyle", region: "campbeltown", foundedYear: 2004 },
    bottlerType: "OB",
    status: "active",
    description:
      "From Glengyle, the distillery revived in 2004 to bring Campbeltown back to three. Mostly bourbon casks with some sherry, bottled at 46%. Lightly smoky, citric and oily, and very hard to keep on the shelf.",
    whisky: { abv: 46, ageYears: 12, region: "campbeltown", caskType: ["ex-bourbon", "ex-sherry"], peatPpm: 15, chillFiltered: false, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_kk12_70", sku: "KK12-70", sizeMl: 700, price: gbp(5295), inStock: true }],
    image: { seed: "kilkerran", alt: "Bottle of Kilkerran 12 Year Old single malt Scotch whisky" },
    flavour: flav({ maritime: 60, smoky: 40, fruity: 50, rich: 45 }),
    tastingNote: {
      nose: "Lemon oil, light smoke and malt.",
      palate: "Oily citrus, honey and a saline thread.",
      finish: "Long, fresh and gently smoky.",
    },
    flavourTags: ["maritime", "smoky", "fruity"],
    ratingAvg: 4.6,
    ratingCount: 0,
    badges: [],
  },
  /* ------------------------------------------------------------------ */
  /* Lowland                                                             */
  /* ------------------------------------------------------------------ */
  {
    id: "p_auchentoshan_tw",
    type: "bottle",
    title: "Auchentoshan Three Wood",
    slug: "auchentoshan-three-wood",
    brand: { id: "b_auchentoshan", name: "Auchentoshan", slug: "auchentoshan" },
    distillery: { id: "d_auchentoshan", name: "Auchentoshan", slug: "auchentoshan", region: "lowland", foundedYear: 1823 },
    bottlerType: "OB",
    status: "active",
    description:
      "Glasgow's triple-distilled malt, moved through bourbon, oloroso and Pedro Ximénez casks in turn. The layering gives butterscotch, raisin and hazelnut on a naturally light spirit. Lowland delicacy with a sherry coat on.",
    whisky: { abv: 43, ageYears: null, region: "lowland", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_auch_tw_70", sku: "AUCH-TW-70", sizeMl: 700, price: gbp(4695), memberPrice: gbp(4225), inStock: true }],
    image: { seed: "auchentoshan-tw", alt: "Bottle of Auchentoshan Three Wood single malt Scotch whisky" },
    flavour: flav({ sweet: 65, rich: 55, fruity: 55, spicy: 30 }),
    tastingNote: {
      nose: "Brown sugar, raisin and orange.",
      palate: "Butterscotch, hazelnut and sherry fruit.",
      finish: "Sweet and rounded.",
    },
    flavourTags: ["sweet", "rich"],
    ratingAvg: 4.2,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_auchentoshan_ao",
    type: "bottle",
    title: "Auchentoshan American Oak",
    slug: "auchentoshan-american-oak",
    brand: { id: "b_auchentoshan", name: "Auchentoshan", slug: "auchentoshan" },
    distillery: { id: "d_auchentoshan", name: "Auchentoshan", slug: "auchentoshan", region: "lowland", foundedYear: 1823 },
    bottlerType: "OB",
    status: "active",
    description:
      "Triple-distilled and matured entirely in first-fill bourbon casks. Vanilla, coconut and citrus, with the light body the Lowlands are known for. As gentle an introduction as Scotch whisky offers.",
    whisky: { abv: 40, ageYears: null, region: "lowland", caskType: ["ex-bourbon"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_auch_ao_70", sku: "AUCH-AO-70", sizeMl: 700, price: gbp(3195), memberPrice: gbp(2875), inStock: true }],
    image: { seed: "auchentoshan-ao", alt: "Bottle of Auchentoshan American Oak single malt Scotch whisky" },
    flavour: flav({ sweet: 60, fruity: 55, floral: 40, rich: 20 }),
    tastingNote: {
      nose: "Vanilla, coconut and citrus zest.",
      palate: "Light, sweet malt with white chocolate.",
      finish: "Short, clean and easy.",
    },
    flavourTags: ["sweet", "beginner"],
    ratingAvg: 4.0,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_glenkinchie12",
    type: "bottle",
    title: "Glenkinchie 12 Year Old",
    slug: "glenkinchie-12-year-old",
    brand: { id: "b_glenkinchie", name: "Glenkinchie", slug: "glenkinchie" },
    distillery: { id: "d_glenkinchie", name: "Glenkinchie", slug: "glenkinchie", region: "lowland", foundedYear: 1825 },
    bottlerType: "OB",
    status: "active",
    description:
      "The Edinburgh malt, twenty minutes from the city in farming country. Grassy, floral and lightly honeyed, it is the classic aperitif whisky: the one to pour before dinner rather than after it.",
    whisky: { abv: 43, ageYears: 12, region: "lowland", caskType: ["ex-bourbon"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_gk12_70", sku: "GK12-70", sizeMl: 700, price: gbp(4495), memberPrice: gbp(4045), inStock: true }],
    image: { seed: "glenkinchie", alt: "Bottle of Glenkinchie 12 Year Old single malt Scotch whisky" },
    flavour: flav({ floral: 65, sweet: 50, fruity: 50, rich: 20 }),
    tastingNote: {
      nose: "Cut grass, blossom and lemon.",
      palate: "Light honey, cereal and orchard fruit.",
      finish: "Crisp and dry.",
    },
    flavourTags: ["floral", "beginner"],
    ratingAvg: 4.1,
    ratingCount: 0,
    badges: [],
  },
  /* ------------------------------------------------------------------ */
  /* Ireland                                                             */
  /* ------------------------------------------------------------------ */
  {
    id: "p_greenspot",
    type: "bottle",
    title: "Green Spot Single Pot Still",
    slug: "green-spot-single-pot-still",
    brand: { id: "b_greenspot", name: "Green Spot", slug: "green-spot" },
    distillery: { id: "d_midleton", name: "Midleton", slug: "midleton", region: "ireland", foundedYear: 1825 },
    bottlerType: "OB",
    status: "active",
    description:
      "A Dublin wine merchant's bottling that survived when nearly every other Irish whiskey died out. Malted and unmalted barley from Midleton, matured in bourbon and sherry casks. Green apple, menthol and that unmistakable pot still spice.",
    whisky: { abv: 40, ageYears: null, region: "ireland", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_gs_70", sku: "GSPOT-70", sizeMl: 700, price: gbp(4295), memberPrice: gbp(3865), inStock: true }],
    image: { seed: "greenspot", alt: "Bottle of Green Spot single pot still Irish whiskey" },
    flavour: flav({ fruity: 65, spicy: 55, sweet: 55, rich: 40 }),
    tastingNote: {
      nose: "Green apple, barley and a hint of menthol.",
      palate: "Creamy orchard fruit and pot still spice.",
      finish: "Lively and clean.",
    },
    flavourTags: ["fruity", "spicy"],
    ratingAvg: 4.4,
    ratingCount: 0,
    badges: ["bestseller"],
  },
  {
    id: "p_bushmills10",
    type: "bottle",
    title: "Bushmills 10 Year Old",
    slug: "bushmills-10-year-old",
    brand: { id: "b_bushmills", name: "Bushmills", slug: "bushmills" },
    distillery: { id: "d_bushmills", name: "Old Bushmills", slug: "bushmills", region: "ireland", foundedYear: 1608 },
    bottlerType: "OB",
    status: "active",
    description:
      "Triple-distilled single malt from the distillery working under a 1608 licence. Ten years mainly in ex-bourbon casks gives honey, vanilla and milk chocolate. Softly spoken and very easy to like.",
    whisky: { abv: 40, ageYears: 10, region: "ireland", caskType: ["ex-bourbon"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_bush10_70", sku: "BUSH10-70", sizeMl: 700, price: gbp(3495), memberPrice: gbp(3145), inStock: true }],
    image: { seed: "bushmills", alt: "Bottle of Bushmills 10 Year Old single malt Irish whiskey" },
    flavour: flav({ sweet: 60, fruity: 55, floral: 35, rich: 30 }),
    tastingNote: {
      nose: "Honey, vanilla and ripe banana.",
      palate: "Milk chocolate, malt and soft fruit.",
      finish: "Gentle and sweet.",
    },
    flavourTags: ["sweet", "fruity", "beginner"],
    ratingAvg: 4.1,
    ratingCount: 0,
    badges: [],
  },
  /* ------------------------------------------------------------------ */
  /* Japan                                                               */
  /* ------------------------------------------------------------------ */
  {
    id: "p_nikka_ftb",
    type: "bottle",
    title: "Nikka From The Barrel",
    slug: "nikka-from-the-barrel",
    brand: { id: "b_nikka", name: "Nikka", slug: "nikka" },
    distillery: { id: "d_nikka", name: "Nikka", slug: "nikka", region: "japan", foundedYear: 1934 },
    bottlerType: "OB",
    status: "active",
    description:
      "A blend of malt and grain from Nikka's Yoichi and Miyagikyo distilleries, married in casks and bottled at 51.4% in a squat little flask. Punches miles above its price. The 50cl bottle is the only small thing about it.",
    whisky: { abv: 51.4, ageYears: null, region: "japan", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_nftb_50", sku: "NFTB-50", sizeMl: 500, price: gbp(3495), memberPrice: gbp(3145), inStock: true }],
    image: { seed: "nikka", alt: "Bottle of Nikka From The Barrel blended Japanese whisky" },
    flavour: flav({ rich: 65, spicy: 60, fruity: 55, sweet: 50 }),
    tastingNote: {
      nose: "Toffee, winter spice and orange peel.",
      palate: "Full and punchy: caramel, oak and dried fruit.",
      finish: "Long, warming and spiced.",
    },
    flavourTags: ["rich", "spicy"],
    ratingAvg: 4.6,
    ratingCount: 0,
    badges: ["bestseller"],
  },
  {
    id: "p_yamazaki12",
    type: "bottle",
    title: "Yamazaki 12 Year Old",
    slug: "yamazaki-12-year-old",
    brand: { id: "b_yamazaki", name: "Yamazaki", slug: "yamazaki" },
    distillery: { id: "d_yamazaki", name: "Yamazaki", slug: "yamazaki", region: "japan", foundedYear: 1923 },
    bottlerType: "OB",
    status: "active",
    description:
      "Japan's first single malt, from the distillery Suntory built in 1923. American, Spanish and Mizunara oak give peach, coconut and that faint temple-incense note nothing else has. Allocated, priced accordingly, and still worth it.",
    whisky: { abv: 43, ageYears: 12, region: "japan", caskType: ["ex-bourbon", "ex-sherry", "mizunara"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_yam12_70", sku: "YAM12-70", sizeMl: 700, price: gbp(15900), inStock: true }],
    image: { seed: "yamazaki", alt: "Bottle of Yamazaki 12 Year Old single malt Japanese whisky" },
    flavour: flav({ fruity: 65, floral: 55, sweet: 55, rich: 45, spicy: 35 }),
    tastingNote: {
      nose: "Peach, pineapple and Mizunara incense.",
      palate: "Coconut, citrus and soft oak spice.",
      finish: "Long, elegant and faintly spiced.",
    },
    flavourTags: ["fruity", "floral", "japanese"],
    ratingAvg: 4.7,
    ratingCount: 0,
    badges: [],
  },
  /* ------------------------------------------------------------------ */
  /* America (bourbon & rye)                                             */
  /* ------------------------------------------------------------------ */
  {
    id: "p_buffalotrace",
    type: "bottle",
    title: "Buffalo Trace Kentucky Straight Bourbon",
    slug: "buffalo-trace-bourbon",
    brand: { id: "b_buffalotrace", name: "Buffalo Trace", slug: "buffalo-trace" },
    distillery: { id: "d_buffalotrace", name: "Buffalo Trace", slug: "buffalo-trace", region: "kentucky" },
    bottlerType: "OB",
    status: "active",
    description:
      "The flagship bourbon from one of Kentucky's great working distilleries. Vanilla, toffee and brown sugar with a peppery edge. At this price it has no business being this good, which is why it keeps selling out.",
    whisky: { abv: 40, ageYears: null, region: "kentucky", caskType: ["new-american-oak"], chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_bt_70", sku: "BT-70", sizeMl: 700, price: gbp(2795), memberPrice: gbp(2515), inStock: true }],
    image: { seed: "buffalotrace", alt: "Bottle of Buffalo Trace Kentucky straight bourbon" },
    flavour: flav({ sweet: 70, spicy: 50, rich: 45, fruity: 35 }),
    tastingNote: {
      nose: "Vanilla, mint and brown sugar.",
      palate: "Toffee, oak and black pepper.",
      finish: "Medium, sweet and spicy.",
    },
    flavourTags: ["sweet", "spicy", "beginner"],
    ratingAvg: 4.3,
    ratingCount: 0,
    badges: ["bestseller"],
  },
  {
    id: "p_makersmark",
    type: "bottle",
    title: "Maker's Mark Kentucky Straight Bourbon",
    slug: "makers-mark-bourbon",
    brand: { id: "b_makersmark", name: "Maker's Mark", slug: "makers-mark" },
    distillery: { id: "d_makersmark", name: "Maker's Mark", slug: "makers-mark", region: "kentucky", foundedYear: 1953 },
    bottlerType: "OB",
    status: "active",
    description:
      "A wheated bourbon: red winter wheat replaces rye in the mash bill, which is why it drinks so soft. Caramel, baking spice and no burn to speak of. The hand-dipped wax seal is the second-best thing about it.",
    whisky: { abv: 45, ageYears: null, region: "kentucky", caskType: ["new-american-oak"], chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_mm_70", sku: "MM-70", sizeMl: 700, price: gbp(2995), memberPrice: gbp(2695), inStock: true }],
    image: { seed: "makersmark", alt: "Bottle of Maker's Mark Kentucky straight bourbon" },
    flavour: flav({ sweet: 75, rich: 45, spicy: 35, fruity: 35 }),
    tastingNote: {
      nose: "Caramel, honey and fresh bread.",
      palate: "Soft vanilla, cinnamon and red fruit.",
      finish: "Smooth and mellow.",
    },
    flavourTags: ["sweet", "beginner"],
    ratingAvg: 4.2,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_woodford",
    type: "bottle",
    title: "Woodford Reserve Distiller's Select",
    slug: "woodford-reserve-distillers-select",
    brand: { id: "b_woodford", name: "Woodford Reserve", slug: "woodford-reserve" },
    distillery: { id: "d_woodford", name: "Woodford Reserve", slug: "woodford-reserve", region: "kentucky" },
    bottlerType: "OB",
    status: "active",
    description:
      "Triple pot-distilled in copper stills, unusual for Kentucky, and bottled at 43.2%. Dried fruit, dark chocolate and rye spice with more polish than most bourbons at the price. The old-fashioned drinker's old fashioned.",
    whisky: { abv: 43.2, ageYears: null, region: "kentucky", caskType: ["new-american-oak"], chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_wr_70", sku: "WR-70", sizeMl: 700, price: gbp(3395), memberPrice: gbp(3055), inStock: true }],
    image: { seed: "woodford", alt: "Bottle of Woodford Reserve Distiller's Select bourbon" },
    flavour: flav({ rich: 55, sweet: 60, spicy: 55, fruity: 40 }),
    tastingNote: {
      nose: "Dried fruit, cocoa and toasted oak.",
      palate: "Dark chocolate, orange and rye spice.",
      finish: "Long and gently spicy.",
    },
    flavourTags: ["rich", "spicy"],
    ratingAvg: 4.3,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_rittenhouse",
    type: "bottle",
    title: "Rittenhouse Straight Rye Bottled-in-Bond",
    slug: "rittenhouse-rye-bottled-in-bond",
    brand: { id: "b_rittenhouse", name: "Rittenhouse", slug: "rittenhouse" },
    distillery: { id: "d_heavenhill", name: "Heaven Hill", slug: "heaven-hill", region: "kentucky", foundedYear: 1935 },
    bottlerType: "OB",
    status: "active",
    description:
      "Bottled-in-bond, which by American law means one distillery, one season, at least four years in wood and exactly 50%. Rye spice, dark caramel and enough backbone to hold any cocktail together. Bartenders buy it by the case.",
    whisky: { abv: 50, ageYears: 4, region: "kentucky", caskType: ["new-american-oak"], chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_rh_70", sku: "RH-70", sizeMl: 700, price: gbp(4295), memberPrice: gbp(3865), inStock: true }],
    image: { seed: "rittenhouse", alt: "Bottle of Rittenhouse straight rye whiskey bottled-in-bond" },
    flavour: flav({ spicy: 80, rich: 55, sweet: 50, fruity: 30 }),
    tastingNote: {
      nose: "Rye bread, clove and caramel.",
      palate: "Peppery spice, cocoa and dark sugar.",
      finish: "Long, dry and spicy.",
    },
    flavourTags: ["spicy", "rich"],
    ratingAvg: 4.4,
    ratingCount: 0,
    badges: [],
  },
  /* ------------------------------------------------------------------ */
  /* Collector tier                                                      */
  /* ------------------------------------------------------------------ */
  {
    id: "p_macallan18",
    type: "bottle",
    title: "The Macallan 18 Year Old Sherry Oak",
    slug: "macallan-18-sherry-oak",
    brand: { id: "b_macallan", name: "The Macallan", slug: "macallan" },
    distillery: { id: "d_macallan", name: "The Macallan", slug: "macallan", region: "speyside", foundedYear: 1824 },
    bottlerType: "OB",
    status: "active",
    story:
      "The 18-year-old Sherry Oak is the bottling that built Macallan's auction reputation. Older vintages trade well above retail, which makes the current release the accessible way in.",
    description:
      "Eighteen years exclusively in sherry-seasoned oak from Jerez. Dried fruit, clove and polished wood in a whisky that manages to be both dense and precise. The reference point for sherried Scotch, and priced like one.",
    whisky: { abv: 43, ageYears: 18, region: "speyside", caskType: ["ex-sherry"], chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_mac18_70", sku: "MAC18-70", sizeMl: 700, price: gbp(29900), inStock: true }],
    image: { seed: "macallan18", alt: "Bottle of The Macallan 18 Year Old Sherry Oak single malt" },
    flavour: flav({ rich: 90, sweet: 60, spicy: 55, fruity: 55 }),
    tastingNote: {
      nose: "Dried fruit, ginger and old polished oak.",
      palate: "Fig, clove and dark chocolate, densely layered.",
      finish: "Very long, warm and drying.",
    },
    flavourTags: ["rich", "sherried", "collector"],
    ratingAvg: 4.7,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_springbank18",
    type: "bottle",
    title: "Springbank 18 Year Old",
    slug: "springbank-18-year-old",
    brand: { id: "b_springbank", name: "Springbank", slug: "springbank" },
    distillery: { id: "d_springbank", name: "Springbank", slug: "springbank", region: "campbeltown", foundedYear: 1828 },
    bottlerType: "OB",
    status: "active",
    story:
      "Springbank's output is tiny and its releases are allocated, so the 18 rarely sits on a shelf for long. On the secondary market it has appreciated steadily for a decade.",
    description:
      "Eighteen years, mostly in sherry casks, from Campbeltown's hand-made distillery. Leather, dark fruit and coastal oil with the faint smoke that runs through everything Springbank makes. Scarce because they genuinely cannot make more.",
    whisky: { abv: 46, ageYears: 18, region: "campbeltown", caskType: ["ex-sherry", "ex-bourbon"], peatPpm: 12, chillFiltered: false, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_sb18_70", sku: "SB18-70", sizeMl: 700, price: gbp(28900), inStock: true }],
    image: { seed: "springbank18", alt: "Bottle of Springbank 18 Year Old single malt Scotch whisky" },
    flavour: flav({ rich: 75, maritime: 65, smoky: 40, fruity: 55, sweet: 45 }),
    tastingNote: {
      nose: "Leather, dark fruit and sea air.",
      palate: "Oily, salted toffee, raisin and soft smoke.",
      finish: "Very long, coastal and complex.",
    },
    flavourTags: ["rich", "maritime", "collector"],
    ratingAvg: 4.8,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_talisker25",
    type: "bottle",
    title: "Talisker 25 Year Old",
    slug: "talisker-25-year-old",
    brand: { id: "b_talisker", name: "Talisker", slug: "talisker" },
    distillery: { id: "d_talisker", name: "Talisker", slug: "talisker", region: "islands", foundedYear: 1830 },
    bottlerType: "OB",
    status: "active",
    story:
      "A quarter century mellows Talisker's pepper into something statelier without losing the sea. Released in limited annual batches; older releases are steady performers at auction.",
    description:
      "Twenty-five years in refill casks lets the Skye character speak slowly: soft smoke, brine and orchard fruit where the 10-year-old spikes pepper. Still bottled at Talisker's signature 45.8%.",
    whisky: { abv: 45.8, ageYears: 25, region: "islands", caskType: ["ex-bourbon"], peatPpm: 20, chillFiltered: false, naturalColour: true, limitedEdition: true },
    variants: [{ id: "v_tal25_70", sku: "TAL25-70", sizeMl: 700, price: gbp(39900), inStock: true }],
    image: { seed: "talisker25", alt: "Bottle of Talisker 25 Year Old single malt Scotch whisky" },
    flavour: flav({ maritime: 75, smoky: 50, peaty: 40, fruity: 55, rich: 55 }),
    tastingNote: {
      nose: "Sea spray, wax and dried apple.",
      palate: "Gentle smoke, brine and honeyed malt.",
      finish: "Long, warming, quietly peppery.",
    },
    flavourTags: ["maritime", "smoky", "collector"],
    ratingAvg: 4.8,
    ratingCount: 0,
    badges: ["limited"],
  },
  {
    id: "p_bowmore25",
    type: "bottle",
    title: "Bowmore 25 Year Old",
    slug: "bowmore-25-year-old",
    brand: { id: "b_bowmore", name: "Bowmore", slug: "bowmore" },
    distillery: { id: "d_bowmore", name: "Bowmore", slug: "bowmore", region: "islay", foundedYear: 1779 },
    bottlerType: "OB",
    status: "active",
    story:
      "Old Bowmore is one of whisky's quiet blue chips: the distillery's aged releases have a long auction record, and the 25 sits at the drinkable end of it.",
    description:
      "A quarter century in bourbon and sherry casks turns Bowmore's smoke into something closer to incense. Tropical fruit, dark chocolate and the ghost of peat. Islay with its voice lowered.",
    whisky: { abv: 43, ageYears: 25, region: "islay", caskType: ["ex-bourbon", "ex-sherry"], peatPpm: 25, chillFiltered: false, naturalColour: true, limitedEdition: true },
    variants: [{ id: "v_bow25_70", sku: "BOW25-70", sizeMl: 700, price: gbp(54900), inStock: true }],
    image: { seed: "bowmore25", alt: "Bottle of Bowmore 25 Year Old single malt Scotch whisky" },
    flavour: flav({ rich: 70, smoky: 45, fruity: 65, sweet: 55, maritime: 45 }),
    tastingNote: {
      nose: "Mango, incense smoke and old oak.",
      palate: "Tropical fruit, dark chocolate and soft peat.",
      finish: "Very long and softly smoky.",
    },
    flavourTags: ["rich", "smoky", "collector"],
    ratingAvg: 4.7,
    ratingCount: 0,
    badges: ["limited"],
  },
  {
    id: "p_yamazaki18",
    type: "bottle",
    title: "Yamazaki 18 Year Old",
    slug: "yamazaki-18-year-old",
    brand: { id: "b_yamazaki", name: "Yamazaki", slug: "yamazaki" },
    distillery: { id: "d_yamazaki", name: "Yamazaki", slug: "yamazaki", region: "japan", foundedYear: 1923 },
    bottlerType: "OB",
    status: "active",
    story:
      "The bottle that announced Japanese whisky to the world's collectors. Allocations shrank as demand grew, and the 18 now changes hands well above its list price almost everywhere.",
    description:
      "Eighteen years across American, Spanish and Mizunara oak. Dried fruit, dark honey and sandalwood in a whisky of unusual depth and stillness. The hardest bottle on this shelf to keep in stock.",
    whisky: { abv: 43, ageYears: 18, region: "japan", caskType: ["ex-sherry", "ex-bourbon", "mizunara"], chillFiltered: true, naturalColour: false, limitedEdition: true },
    variants: [{ id: "v_yam18_70", sku: "YAM18-70", sizeMl: 700, price: gbp(74900), inStock: true }],
    image: { seed: "yamazaki18", alt: "Bottle of Yamazaki 18 Year Old single malt Japanese whisky" },
    flavour: flav({ rich: 80, fruity: 60, sweet: 55, floral: 45, spicy: 40 }),
    tastingNote: {
      nose: "Raisin, dark honey and sandalwood.",
      palate: "Sherry fruit, bitter chocolate and Mizunara spice.",
      finish: "Absurdly long and layered.",
    },
    flavourTags: ["rich", "japanese", "collector"],
    ratingAvg: 4.9,
    ratingCount: 0,
    badges: ["limited"],
  },
  /* ------------------------------------------------------------------ */
  /* Tasting flights                                                     */
  /* ------------------------------------------------------------------ */
  {
    id: "p_speyside_flight",
    type: "sample",
    title: "Speyside Explorer: Tasting Flight (4 × 3cl)",
    slug: "speyside-explorer-tasting-flight",
    brand: { id: "b_whiskymart", name: "WhiskyMart Selection", slug: "whiskymart-selection" },
    bottlerType: "NA",
    status: "active",
    description:
      "Four 3cl drams that walk the Speyside style from soft and fruity to fully sherried. Includes Glenfiddich 12, The Glenlivet 12, The Balvenie DoubleWood 12 and The GlenDronach 12.",
    whisky: { abv: 41, ageYears: null, region: "speyside", caskType: [], limitedEdition: false },
    variants: [{ id: "v_flight_spey", sku: "FLIGHT-SPEY", sizeMl: 120, price: gbp(2295), inStock: true }],
    image: { seed: "speyside-flight", alt: "Speyside whisky tasting flight of four 3cl samples" },
    flavour: flav({ sweet: 65, fruity: 65, rich: 45 }),
    flavourTags: ["sweet", "fruity", "sample", "flight"],
    ratingAvg: 4.6,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_world_flight",
    type: "sample",
    title: "Around the World: Tasting Flight (4 × 3cl)",
    slug: "around-the-world-tasting-flight",
    brand: { id: "b_whiskymart", name: "WhiskyMart Selection", slug: "whiskymart-selection" },
    bottlerType: "NA",
    status: "active",
    description:
      "One evening, four whisky countries. A Speyside single malt, an Irish pot still, a Japanese blend and a Kentucky bourbon, poured side by side so the differences explain themselves.",
    whisky: { abv: 44, ageYears: null, region: "world", caskType: [], limitedEdition: false },
    variants: [{ id: "v_flight_world", sku: "FLIGHT-WORLD", sizeMl: 120, price: gbp(2695), inStock: true }],
    image: { seed: "world-flight", alt: "International whisky tasting flight of four 3cl samples" },
    flavour: flav({ sweet: 55, fruity: 55, spicy: 50, rich: 45 }),
    flavourTags: ["sample", "flight"],
    ratingAvg: 4.5,
    ratingCount: 0,
    badges: ["new"],
  },
  {
    id: "p_beginner_flight",
    type: "sample",
    title: "First Drams: A Beginner's Flight (4 × 3cl)",
    slug: "first-drams-beginners-flight",
    brand: { id: "b_whiskymart", name: "WhiskyMart Selection", slug: "whiskymart-selection" },
    bottlerType: "NA",
    status: "active",
    description:
      "Four gentle, well-made drams chosen for a first proper tasting: nothing aggressive, nothing obscure. Includes tasting notes written for people who have never been told what \"waxy\" means.",
    whisky: { abv: 40, ageYears: null, region: "world", caskType: [], limitedEdition: false },
    variants: [{ id: "v_flight_first", sku: "FLIGHT-FIRST", sizeMl: 120, price: gbp(1995), inStock: true }],
    image: { seed: "first-flight", alt: "Beginner's whisky tasting flight of four 3cl samples" },
    flavour: flav({ sweet: 60, fruity: 55, floral: 35 }),
    flavourTags: ["sample", "flight", "beginner"],
    ratingAvg: 4.7,
    ratingCount: 0,
    badges: [],
  },
  /* ------------------------------------------------------------------ */
  /* Glassware & accessories                                             */
  /* ------------------------------------------------------------------ */
  {
    id: "p_glencairn_jug",
    type: "accessory",
    title: "Glencairn Crystal Water Jug",
    slug: "glencairn-crystal-water-jug",
    brand: { id: "b_glencairn", name: "Glencairn", slug: "glencairn" },
    bottlerType: "NA",
    status: "active",
    description:
      "The companion piece to the tasting glass: a small crystal jug for adding water a few drops at a time. A splash of water opens most whiskies; this makes the splash precise.",
    variants: [{ id: "v_glen_jug", sku: "GLEN-JUG", sizeMl: 0, price: gbp(2295), inStock: true }],
    image: { seed: "glencairn-jug", alt: "Glencairn crystal whisky water jug" },
    flavourTags: ["accessory", "glassware"],
    ratingAvg: 4.7,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_wm_decanter",
    type: "accessory",
    title: "WhiskyMart Crystal Decanter",
    slug: "whiskymart-crystal-decanter",
    brand: { id: "b_whiskymart", name: "WhiskyMart Selection", slug: "whiskymart-selection" },
    bottlerType: "NA",
    status: "active",
    description:
      "A heavy-based crystal decanter with a ground-glass stopper, holding a full 70cl bottle. Decanting does nothing chemical to whisky; it just looks tremendous on a shelf, and that counts for something.",
    variants: [{ id: "v_wm_dec", sku: "WM-DEC", sizeMl: 0, price: gbp(5995), inStock: true }],
    image: { seed: "decanter", alt: "Crystal whisky decanter with ground-glass stopper" },
    flavourTags: ["accessory", "glassware"],
    ratingAvg: 4.5,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_wm_dropper",
    type: "accessory",
    title: "Copper Water Dropper",
    slug: "copper-water-dropper",
    brand: { id: "b_whiskymart", name: "WhiskyMart Selection", slug: "whiskymart-selection" },
    bottlerType: "NA",
    status: "active",
    description:
      "A copper pipette for adding water to cask-strength whisky one drop at a time. Cheap, useful and better looking than a teaspoon.",
    variants: [{ id: "v_wm_drop", sku: "WM-DROP", sizeMl: 0, price: gbp(1295), inStock: true }],
    image: { seed: "dropper", alt: "Copper whisky water dropper pipette" },
    flavourTags: ["accessory"],
    ratingAvg: 4.4,
    ratingCount: 0,
    badges: [],
  },
  {
    id: "p_wm_journal",
    type: "accessory",
    title: "Pocket Tasting Journal",
    slug: "pocket-tasting-journal",
    brand: { id: "b_whiskymart", name: "WhiskyMart Selection", slug: "whiskymart-selection" },
    bottlerType: "NA",
    status: "active",
    description:
      "A pocket notebook laid out for tasting notes: space for the bottle, the nose, the palate, the finish and a score. Memory is a poor cellar. Write it down.",
    variants: [{ id: "v_wm_journal", sku: "WM-JOURNAL", sizeMl: 0, price: gbp(995), inStock: true }],
    image: { seed: "journal", alt: "Pocket whisky tasting journal notebook" },
    flavourTags: ["accessory"],
    ratingAvg: 4.6,
    ratingCount: 0,
    badges: [],
  },
];
