import type { Product, Money, FlavourProfile } from "@whiskymart/types";

/* Small builders to keep the seed data readable. */
const gbp = (amount: number): Money => ({ amount, currency: "GBP" });

const flav = (p: Partial<FlavourProfile>): FlavourProfile => ({
  smoky: 0,
  peaty: 0,
  sweet: 0,
  fruity: 0,
  spicy: 0,
  floral: 0,
  maritime: 0,
  rich: 0,
  ...p,
});

/**
 * Seed catalogue. This is a stand-in for the real product service (Medusa /
 * API). The repository ({@link ./repository}) is the only thing that touches
 * it, so swapping the source later requires no UI changes.
 */
export const SEED_PRODUCTS: Product[] = [
  {
    id: "p_lagavulin16",
    type: "bottle",
    title: "Lagavulin 16 Year Old",
    slug: "lagavulin-16-year-old",
    brand: { id: "b_lagavulin", name: "Lagavulin", slug: "lagavulin" },
    distillery: { id: "d_lagavulin", name: "Lagavulin", slug: "lagavulin", region: "islay", foundedYear: 1816 },
    bottlerType: "OB",
    status: "active",
    description:
      "A towering Islay single malt — deep, dry and smoky, with the seaweed-led peat Lagavulin is famous for, balanced by rich sweetness and a long, elegant finish.",
    story:
      "Matured for sixteen years on the southern shore of Islay, this is the benchmark by which peated whiskies are judged.",
    whisky: { abv: 43, ageYears: 16, region: "islay", caskType: ["ex-bourbon"], peatPpm: 35, chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [
      { id: "v_lag16_70", sku: "LAG16-70", sizeMl: 700, price: gbp(7495), memberPrice: gbp(6745), inStock: true },
      { id: "v_lag16_3cl", sku: "LAG16-3CL", sizeMl: 30, price: gbp(695), inStock: true },
    ],
    image: { seed: "lagavulin", alt: "Bottle of Lagavulin 16 Year Old single malt Scotch whisky" },
    flavour: flav({ smoky: 85, peaty: 80, maritime: 70, sweet: 40, rich: 55 }),
    tastingNote: {
      nose: "Intense peat smoke with iodine and seaweed, layered over rich sweetness.",
      palate: "Dry, powerful smoke with sea salt, sherry and a touch of espresso.",
      finish: "Long, elegant and smoky.",
    },
    flavourTags: ["smoky", "peaty", "maritime"],
    ratingAvg: 4.7,
    ratingCount: 212,
    badges: ["bestseller", "award"],
  },
  {
    id: "p_glenfiddich12",
    type: "bottle",
    title: "Glenfiddich 12 Year Old",
    slug: "glenfiddich-12-year-old",
    brand: { id: "b_glenfiddich", name: "Glenfiddich", slug: "glenfiddich" },
    distillery: { id: "d_glenfiddich", name: "Glenfiddich", slug: "glenfiddich", region: "speyside", foundedYear: 1887 },
    bottlerType: "OB",
    status: "active",
    description:
      "The world's most-awarded single malt and a perfect first step into Speyside — fresh, fruity and beautifully balanced with a signature note of pear.",
    whisky: { abv: 40, ageYears: 12, region: "speyside", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_gf12_70", sku: "GF12-70", sizeMl: 700, price: gbp(3995), memberPrice: gbp(3595), inStock: true }],
    image: { seed: "glenfiddich", alt: "Bottle of Glenfiddich 12 Year Old single malt Scotch whisky" },
    flavour: flav({ sweet: 65, fruity: 75, floral: 45, rich: 30 }),
    tastingNote: {
      nose: "Fresh pear and subtle oak.",
      palate: "Sweet, fruity and creamy with a hint of butterscotch.",
      finish: "Long and mellow.",
    },
    flavourTags: ["sweet", "fruity", "beginner"],
    ratingAvg: 4.5,
    ratingCount: 488,
    badges: ["bestseller"],
  },
  {
    id: "p_ardbeg10",
    type: "bottle",
    title: "Ardbeg 10 Year Old",
    slug: "ardbeg-10-year-old",
    brand: { id: "b_ardbeg", name: "Ardbeg", slug: "ardbeg" },
    distillery: { id: "d_ardbeg", name: "Ardbeg", slug: "ardbeg", region: "islay", foundedYear: 1815 },
    bottlerType: "OB",
    status: "active",
    description:
      "A cult Islay classic, bottled at 46% and non-chill-filtered. Uncompromising peat smoke wrapped around surprising notes of lime, pear and vanilla.",
    whisky: { abv: 46, ageYears: 10, region: "islay", caskType: ["ex-bourbon"], peatPpm: 55, chillFiltered: false, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_ard10_70", sku: "ARD10-70", sizeMl: 700, price: gbp(5295), memberPrice: gbp(4895), inStock: true }],
    image: { seed: "ardbeg", alt: "Bottle of Ardbeg 10 Year Old single malt Scotch whisky" },
    flavour: flav({ smoky: 90, peaty: 88, maritime: 55, sweet: 35, fruity: 40 }),
    tastingNote: {
      nose: "Smoke, tar and zesty citrus.",
      palate: "Powerful peat with espresso, pear and a savoury edge.",
      finish: "Very long and smoky.",
    },
    flavourTags: ["smoky", "peaty"],
    ratingAvg: 4.8,
    ratingCount: 357,
    badges: ["award"],
  },
  {
    id: "p_glenmorangie10",
    type: "bottle",
    title: "Glenmorangie The Original 10 Year Old",
    slug: "glenmorangie-original-10",
    brand: { id: "b_glenmorangie", name: "Glenmorangie", slug: "glenmorangie" },
    distillery: { id: "d_glenmorangie", name: "Glenmorangie", slug: "glenmorangie", region: "highland", foundedYear: 1843 },
    bottlerType: "OB",
    status: "active",
    description:
      "Distilled at Scotland's tallest stills for a delicate, elegant spirit. Floral and citrus-led with peach, vanilla and a creamy texture.",
    whisky: { abv: 40, ageYears: 10, region: "highland", caskType: ["ex-bourbon"], chillFiltered: true, naturalColour: false, limitedEdition: false },
    variants: [{ id: "v_glm10_70", sku: "GLM10-70", sizeMl: 700, price: gbp(3795), memberPrice: gbp(3415), inStock: true }],
    image: { seed: "glenmorangie", alt: "Bottle of Glenmorangie The Original 10 Year Old single malt" },
    flavour: flav({ floral: 80, fruity: 70, sweet: 55, spicy: 25 }),
    tastingNote: {
      nose: "Peach, citrus and floral honey.",
      palate: "Vanilla, orange and a creamy malt sweetness.",
      finish: "Clean and fragrant.",
    },
    flavourTags: ["floral", "fruity", "beginner"],
    ratingAvg: 4.4,
    ratingCount: 274,
    badges: [],
  },
  {
    id: "p_macallan12",
    type: "bottle",
    title: "The Macallan 12 Year Old Sherry Oak",
    slug: "macallan-12-sherry-oak",
    brand: { id: "b_macallan", name: "The Macallan", slug: "macallan" },
    distillery: { id: "d_macallan", name: "The Macallan", slug: "macallan", region: "speyside", foundedYear: 1824 },
    bottlerType: "OB",
    status: "active",
    description:
      "Matured exclusively in hand-picked sherry-seasoned oak casks from Jerez. Rich, full-bodied and unmistakably Macallan — dried fruit, ginger and Christmas spice.",
    whisky: { abv: 40, ageYears: 12, region: "speyside", caskType: ["ex-sherry"], chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_mac12_70", sku: "MAC12-70", sizeMl: 700, price: gbp(8495), memberPrice: gbp(7645), inStock: true }],
    image: { seed: "macallan", alt: "Bottle of The Macallan 12 Year Old Sherry Oak single malt" },
    flavour: flav({ rich: 85, sweet: 60, spicy: 55, fruity: 50 }),
    tastingNote: {
      nose: "Dried fruits, sherry and wood smoke.",
      palate: "Rich, full and rounded with ginger and dried fruit.",
      finish: "Sweet oak, long.",
    },
    flavourTags: ["rich", "sherried"],
    ratingAvg: 4.6,
    ratingCount: 401,
    badges: ["exclusive", "bestseller"],
  },
  {
    id: "p_talisker10",
    type: "bottle",
    title: "Talisker 10 Year Old",
    slug: "talisker-10-year-old",
    brand: { id: "b_talisker", name: "Talisker", slug: "talisker" },
    distillery: { id: "d_talisker", name: "Talisker", slug: "talisker", region: "islands", foundedYear: 1830 },
    bottlerType: "OB",
    status: "active",
    description:
      "The classic maritime malt from the Isle of Skye — peppery smoke, brine and a famous pinch of sea salt, with warming sweetness underneath.",
    whisky: { abv: 45.8, ageYears: 10, region: "islands", caskType: ["ex-bourbon"], peatPpm: 25, chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_tal10_70", sku: "TAL10-70", sizeMl: 700, price: gbp(4495), memberPrice: gbp(4045), inStock: true }],
    image: { seed: "talisker", alt: "Bottle of Talisker 10 Year Old single malt Scotch whisky" },
    flavour: flav({ smoky: 60, maritime: 80, spicy: 65, sweet: 40 }),
    tastingNote: {
      nose: "Sea spray, smoke and citrus.",
      palate: "Peppery smoke, brine and barley sweetness.",
      finish: "Warm with a peppery kick.",
    },
    flavourTags: ["maritime", "smoky", "spicy"],
    ratingAvg: 4.6,
    ratingCount: 319,
    badges: ["bestseller"],
  },
  {
    id: "p_redbreast12",
    type: "bottle",
    title: "Redbreast 12 Year Old",
    slug: "redbreast-12-year-old",
    brand: { id: "b_redbreast", name: "Redbreast", slug: "redbreast" },
    distillery: { id: "d_midleton", name: "Midleton", slug: "midleton", region: "ireland", foundedYear: 1825 },
    bottlerType: "OB",
    status: "active",
    description:
      "The definitive single pot still Irish whiskey. Full and complex, with the spicy, creamy character that only pot still distillation delivers.",
    whisky: { abv: 40, ageYears: 12, region: "ireland", caskType: ["ex-bourbon", "ex-sherry"], chillFiltered: true, naturalColour: true, limitedEdition: false },
    variants: [{ id: "v_rb12_70", sku: "RB12-70", sizeMl: 700, price: gbp(5995), memberPrice: gbp(5395), inStock: true }],
    image: { seed: "redbreast", alt: "Bottle of Redbreast 12 Year Old single pot still Irish whiskey" },
    flavour: flav({ rich: 70, fruity: 65, spicy: 60, sweet: 55 }),
    tastingNote: {
      nose: "Dried fruit, toasted oak and pot still spices.",
      palate: "Full and creamy with sherry, nuts and spice.",
      finish: "Satisfying and long.",
    },
    flavourTags: ["rich", "spicy", "fruity"],
    ratingAvg: 4.7,
    ratingCount: 263,
    badges: ["award"],
  },
  {
    id: "p_hibiki_harmony",
    type: "bottle",
    title: "Hibiki Japanese Harmony",
    slug: "hibiki-japanese-harmony",
    brand: { id: "b_hibiki", name: "Hibiki", slug: "hibiki" },
    distillery: { id: "d_suntory", name: "Suntory", slug: "suntory", region: "japan", foundedYear: 1923 },
    bottlerType: "OB",
    status: "active",
    description:
      "A blend of malt and grain whiskies from Suntory's Yamazaki, Hakushu and Chita distilleries. Delicate, harmonious and subtly floral.",
    whisky: { abv: 43, ageYears: null, region: "japan", caskType: ["ex-bourbon", "ex-sherry", "mizunara"], chillFiltered: true, naturalColour: false, limitedEdition: true },
    variants: [{ id: "v_hib_70", sku: "HIB-70", sizeMl: 700, price: gbp(8995), memberPrice: gbp(8095), inStock: true }],
    image: { seed: "hibiki", alt: "Bottle of Hibiki Japanese Harmony blended whisky" },
    flavour: flav({ floral: 75, fruity: 60, sweet: 55, rich: 40 }),
    tastingNote: {
      nose: "Rose, lychee and a hint of sandalwood.",
      palate: "Honey, candied orange and white chocolate.",
      finish: "Subtle Mizunara oak.",
    },
    flavourTags: ["floral", "delicate", "japanese"],
    ratingAvg: 4.5,
    ratingCount: 158,
    badges: ["limited", "new"],
  },
  {
    id: "p_islay_flight",
    type: "sample",
    title: "Islay Discovery — Tasting Flight (4 × 3cl)",
    slug: "islay-discovery-tasting-flight",
    brand: { id: "b_whiskymart", name: "WhiskyMart Selection", slug: "whiskymart-selection" },
    bottlerType: "NA",
    status: "active",
    description:
      "Four 3cl samples of benchmark Islay malts — a low-risk way to find your favourite before committing to a full bottle. Includes Lagavulin, Ardbeg, Laphroaig and Bowmore.",
    whisky: { abv: 46, ageYears: null, region: "islay", caskType: [], peatPpm: 50, limitedEdition: false },
    variants: [{ id: "v_flight_islay", sku: "FLIGHT-ISLAY", sizeMl: 120, price: gbp(2495), inStock: true }],
    image: { seed: "islay-flight", alt: "Islay whisky tasting flight of four 3cl samples" },
    flavour: flav({ smoky: 85, peaty: 82, maritime: 60 }),
    flavourTags: ["smoky", "peaty", "sample", "flight"],
    ratingAvg: 4.8,
    ratingCount: 96,
    badges: ["new"],
  },
  {
    id: "p_glencairn_glass",
    type: "accessory",
    title: "Glencairn Crystal Whisky Glass (Set of 2)",
    slug: "glencairn-whisky-glass-set-of-2",
    brand: { id: "b_glencairn", name: "Glencairn", slug: "glencairn" },
    bottlerType: "NA",
    status: "active",
    description:
      "The official whisky nosing and tasting glass, designed to concentrate aromas. Tapered mouth, solid base, dishwasher safe. Sold as a set of two.",
    variants: [{ id: "v_glencairn_2", sku: "GLEN-GLASS-2", sizeMl: 0, price: gbp(1600), inStock: true }],
    image: { seed: "glencairn", alt: "Set of two Glencairn crystal whisky tasting glasses" },
    flavourTags: ["accessory", "glassware"],
    ratingAvg: 4.9,
    ratingCount: 134,
    badges: [],
  },
];
